---
version: '2.1'
services:
  airdcpp:
    image: gangefors/airdcpp-webclient
    volumes:
      - airdcpp:/.airdcpp
    environment:
      - PUID=${UID:-0}
      - PGID=${GID:-0}
    hostname: airdcpp
    ports:
      - ${HTTP_PORT:-80}:5600
      - ${HTTPS_PORT:-443}:5601
      - ${TCP_PORT:-21248}:${TCP_PORT:-21248}
      - ${UDP_PORT:-21248}:${UDP_PORT:-21248}/udp
      - ${TLS_PORT:-21249}:${TLS_PORT:-21249}

volumes:
  airdcpp:
    driver: local
