name: Build and push Docker image on new release
on:
  workflow_dispatch:
jobs:
  buildDockerImage:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get latest airdcpp release
        id: airdcpp-release
        run: |
          local current_release=$(curl -sL https://api.github.com/repos/airdcpp-web/airdcpp-webclient/releases/latest | jq -r ".tag_name")
          curl -s "https://hub.docker.com/v2/repositories/gangefors/airdcpp-webclient/tags/?page_size=10&ordering=last_updated" | jq '.results[].name' | grep -q "${current_release}"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          no-cache: true
          push: true
          tags: |
            gangefors/airdcpp-webclient:latest-test
            gangefors/airdcpp-webclient:${{ steps.airdcpp-release.outputs.release_tag }}-test
