name: docker-build

on:
  push:
    branches:
      - master

jobs:
  multi-arch-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - 
        name: Login to GitHub Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PERSONAL_TOKEN }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
         name: Get Latest Tag
         id: previoustag
         uses: WyriHaximus/github-action-get-previous-tag@1.0.0
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./linux-arm64.Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/airdcpp:latest
            ${{ secrets.DOCKER_USER }}/airdcpp:${{ steps.previoustag.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/airdcpp:latest
            ghcr.io/${{ github.repository_owner }}/airdcpp:${{ steps.previoustag.outputs.tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
